# Generated by Django 4.2 on 2026-04-29 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote sur Sujet',
                'verbose_name_plural': 'Votes sur Sujets',
                'ordering': ['-created_at'],
                'unique_together': {('topic', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReplyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote sur Réponse',
                'verbose_name_plural': 'Votes sur Réponses',
                'ordering': ['-created_at'],
                'unique_together': {('reply', 'user')},
            },
        ),
    ]
