# Generated by Django 6.0.3 on 2026-05-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyVote',
        ),
    ]
