# Generated by Django 6.0.5 on 2026-05-06 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_remove_report_moderation__status_2a84ce_idx_and_more'),
        ('notifications', '0002_notification_actor_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='moderation.report'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reply', 'Nouvelle réponse'), ('report', 'Contenu signalé'), ('best_answer', 'Meilleure réponse')], default='reply', max_length=20),
        ),
    ]
