# Generated by Django 6.0.3 on 2026-05-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_reply_author_remove_reply_topic_and_more'),
        ('moderation', '0002_remove_report_reply_alter_report_topic'),
        ('votes', '0002_delete_replyvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
