# Generated by Django 6.0.3 on 2026-05-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_delete_reply'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
    ]
