# Generated by Django 6.0.3 on 2026-05-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='hidden_reason',
            field=models.CharField(blank=True, help_text='Raison du masquage', max_length=255),
        ),
        migrations.AddField(
            model_name='topic',
            name='hidden_reason',
            field=models.CharField(blank=True, help_text='Raison du masquage', max_length=255),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Sujet masqué par la modération'),
        ),
    ]
