# Generated by Django 6.0.3 on 2026-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_reply_hidden_reason_topic_hidden_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Sujet masqué par modération'),
        ),
    ]
