# Generated by Django 6.0.3 on 2026-05-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_reply_author_remove_reply_topic_and_more'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reply',
        ),
        migrations.AlterField(
            model_name='report',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.topic'),
        ),
    ]
