# Generated by Django 6.0.3 on 2026-05-06 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('moderation', '0003_remove_report_topic_report_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='moderation__status_2a84ce_idx',
        ),
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='report',
            name='details',
            field=models.TextField(blank=True, help_text='Détails supplémentaires du signalement'),
        ),
        migrations.AlterField(
            model_name='report',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Contenu inapproprié'), ('harassment', 'Harcèlement'), ('misinformation', 'Désinformation'), ('copyright', 'Violation de droits'), ('other', 'Autre')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Notes de résolution'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='moderation__status_282342_idx'),
        ),
    ]
