# Generated by Django 6.0.3 on 2026-05-04 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text="Avatar de l'utilisateur", null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='Biographie courte', max_length=500)),
                ('signature', models.CharField(blank=True, help_text="Signature de l'utilisateur", max_length=255)),
                ('filiere', models.CharField(blank=True, help_text="Filière d'études", max_length=100)),
                ('promotion', models.CharField(blank=True, help_text='Année de promotion', max_length=50)),
                ('reputation', models.IntegerField(default=0, help_text='Points de réputation')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('moderator', 'Modérateur'), ('admin', 'Administrateur')], default='user', help_text='Rôle utilisateur', max_length=20)),
                ('is_banned', models.BooleanField(default=False, help_text='Utilisateur banni?')),
                ('banned_until', models.DateTimeField(blank=True, help_text='Date de fin du bannissement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
