# Generated by Django 4.2 on 2026-04-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, help_text="URL de l'image d'avatar"),
        ),
    ]
